"""基于同目录临时文件发布产物；调用方负责在测量窗口之外写入。"""
from __future__ import annotations

import json
import os
from pathlib import Path
import stat
import tempfile
from typing import Any, Callable, TextIO


def require_schema_version(payload: Any, expected: int, artifact: str) -> None:
    """在消费产物前拒绝缺失、过期或未知的协议版本。"""
    version = payload.get("schema_version") if isinstance(payload, dict) else None
    if type(version) is not int or version != expected:
        raise ValueError(
            f"{artifact}: unsupported schema_version={version!r}; expected {expected}. "
            "Use artifacts generated by the current AC-Prof version."
        )


def read_static_metadata(result_dir: str | Path, *, required: bool = False) -> dict:
    """读取当前静态元数据；旧 CSV 和内嵌采集历史均不能自动转换。"""
    from acprof.config import STATIC_META_SCHEMA_VERSION
    directory = Path(result_dir)
    path = directory / "static_meta.json"
    if not path.is_file():
        if (directory / "static_meta.csv").exists():
            raise ValueError("static_meta.csv is no longer supported; regenerate current result artifacts")
        if required:
            raise FileNotFoundError(path)
        return {}
    payload = json.loads(path.read_text(encoding="utf-8"))
    require_schema_version(payload, STATIC_META_SCHEMA_VERSION, str(path))
    history = [key for key in payload if key.endswith(("_history", "_last_run"))]
    if history:
        raise ValueError(f"{path}: collection history must be in collection_history.json: {history}")
    return payload


def atomic_write(path: str | Path, write: Callable[[TextIO], None]) -> None:
    destination = Path(path)
    destination.parent.mkdir(parents=True, exist_ok=True)
    mode = stat.S_IMODE(destination.stat().st_mode) if destination.exists() else 0o644
    temporary = None
    try:
        with tempfile.NamedTemporaryFile(mode="w", encoding="utf-8", newline="",
                                         dir=destination.parent, prefix=f".{destination.name}.",
                                         suffix=".tmp", delete=False) as stream:
            temporary = Path(stream.name)
            write(stream)
            stream.flush()
            os.fchmod(stream.fileno(), mode)
            os.fsync(stream.fileno())
        os.replace(temporary, destination)
        temporary = None
        if os.name == "posix":
            directory_fd = os.open(destination.parent, os.O_RDONLY | os.O_DIRECTORY)
            try:
                os.fsync(directory_fd)
            finally:
                os.close(directory_fd)
    finally:
        if temporary is not None:
            temporary.unlink(missing_ok=True)


def atomic_write_json(path: str | Path, payload: Any) -> None:
    def write(stream: TextIO) -> None:
        json.dump(payload, stream, ensure_ascii=False, indent=2, allow_nan=False)
        stream.write("\n")
    atomic_write(path, write)
