"""CSV 指标的唯一登记表；标准库声明，不初始化任何采集器。"""
from __future__ import annotations

from dataclasses import asdict, dataclass
from types import MappingProxyType


@dataclass(frozen=True)
class Metric:
    name: str
    unit: str
    source: str
    window: str
    applicability: str = "all"
    kind: str = "number"
    tool: str = ""
    posthoc: bool = False

    def to_dict(self):
        return asdict(self)


# 顺序就是 CSV 协议顺序；单位和窗口在此显式声明，消费者不得按列名猜测。
_DECLARATIONS = (
    Metric('cpu_cores', 'core', 'protocol', 'case'),
    Metric('mem_cap_gb', 'GiB', 'protocol', 'case'),
    Metric('gpu_mode', 'text', 'protocol', 'case', applicability='gpu', kind='text'),
    Metric('input_scale', 'input_scale_type', 'protocol', 'row'),
    Metric('input_units_per_request', 'input_unit/request', 'input_plan', 'materialized_request'),
    Metric('input_num_samples', 'sample/request', 'input_plan', 'materialized_request', applicability='audio'),
    Metric('input_pixels_per_request', 'pixel/request', 'input_plan', 'materialized_request', applicability='pixel_geometry'),
    Metric('output_pixels_per_request', 'pixel/request', 'input_plan', 'materialized_request', applicability='pixel_geometry'),
    Metric('request_payload_bytes', 'byte/request', 'client_http', 'request_window'),
    Metric('packet_request_wire_bytes_per_request', 'byte/request', 'pcap', 'request_window'),
    Metric('packet_response_wire_bytes_per_request', 'byte/request', 'pcap', 'request_window'),
    Metric('packet_total_wire_bytes_per_request', 'byte/request', 'pcap', 'request_window'),
    Metric('packet_tcp_payload_bytes_per_request', 'byte/request', 'pcap', 'request_window'),
    Metric('packet_protocol_overhead_bytes_per_request', 'byte/request', 'pcap', 'request_window'),
    Metric('packet_protocol_overhead_ratio', 'ratio', 'pcap', 'request_window'),
    Metric('task_param', 'text', 'protocol', 'row', kind='text'),
    Metric('output_length_avg', 'task_output_unit/request', 'client_http', 'request_window'),
    Metric('output_token_count_avg', 'token/request', 'client_http', 'request_window', applicability='text_tokenizer'),
    Metric('repeat_idx', 'index', 'protocol', 'row'),
    Metric('warmup', '0|1', 'protocol', 'row'),
    Metric('repeat_in_window', 'request/window', 'protocol', 'row'),
    Metric('latency_s', 's', 'pcap', 'request_window'),
    Metric('latency_s_per_input_unit', 's/input_unit', 'pcap', 'request_window'),
    Metric('latency_s_per_input_megapixel', 's/Mpixel', 'pcap', 'request_window', applicability='pixel_geometry'),
    Metric('latency_s_per_output_megapixel', 's/Mpixel', 'pcap', 'request_window', applicability='pixel_geometry'),
    Metric('latency_request_count', 'request/window', 'pcap', 'request_window'),
    Metric('latency_p50_s', 's', 'pcap', 'request_window'),
    Metric('latency_p90_s', 's', 'pcap', 'request_window'),
    Metric('latency_p95_s', 's', 'pcap', 'request_window'),
    Metric('latency_std_s', 's', 'pcap', 'request_window'),
    Metric('latency_cv', 'ratio', 'pcap', 'request_window'),
    Metric('latency_iqr_s', 's', 'pcap', 'request_window'),
    Metric('latency_max_s', 's', 'pcap', 'request_window'),
    Metric('latency_slow_ratio', 'ratio', 'pcap', 'request_window'),
    Metric('latency_app_s', 's', 'client_http', 'request_window'),
    Metric('latency_app_s_per_input_unit', 's/input_unit', 'client_http', 'request_window'),
    Metric('latency_app_s_per_input_megapixel', 's/Mpixel', 'client_http', 'request_window', applicability='pixel_geometry'),
    Metric('latency_app_s_per_output_megapixel', 's/Mpixel', 'client_http', 'request_window', applicability='pixel_geometry'),
    Metric('latency_app_request_count', 'request/window', 'client_http', 'request_window'),
    Metric('latency_app_p50_s', 's', 'client_http', 'request_window'),
    Metric('latency_app_p90_s', 's', 'client_http', 'request_window'),
    Metric('latency_app_p95_s', 's', 'client_http', 'request_window'),
    Metric('latency_app_std_s', 's', 'client_http', 'request_window'),
    Metric('latency_app_cv', 'ratio', 'client_http', 'request_window'),
    Metric('latency_app_iqr_s', 's', 'client_http', 'request_window'),
    Metric('latency_app_max_s', 's', 'client_http', 'request_window'),
    Metric('latency_app_slow_ratio', 'ratio', 'client_http', 'request_window'),
    Metric('throughput_samples_per_s', 'sample/s', 'derived', 'request_window'),
    Metric('throughput_samples_per_s_per_cpu_core', 'sample/s/core', 'derived', 'request_window'),
    Metric('model_logical_mflop_per_request_torch_profiler_eager', 'MFLOP/request', 'torch', 'independent_profiler', tool='torch', posthoc=True),
    Metric('model_logical_mflops_app_torch_profiler_eager', 'MFLOP/s', 'torch', 'independent_profiler', tool='torch'),
    Metric('model_logical_mflops_packet_torch_profiler_eager', 'MFLOP/s', 'torch', 'independent_profiler', tool='torch'),
    Metric('compute_profile_error_torch_profiler_eager', 'text', 'torch', 'independent_profiler', kind='text', tool='torch', posthoc=True),
    Metric('gpu_executed_mflop_per_request_ncu', 'MFLOP/request', 'ncu', 'independent_profiler', applicability='gpu', tool='ncu', posthoc=True),
    Metric('gpu_executed_tensor_mflop_per_request_ncu', 'MFLOP/request', 'ncu', 'independent_profiler', applicability='gpu', tool='ncu', posthoc=True),
    Metric('gpu_executed_scalar_mflop_per_request_ncu', 'MFLOP/request', 'ncu', 'independent_profiler', applicability='gpu', tool='ncu', posthoc=True),
    Metric('gpu_executed_tensor_share_pct_ncu', '%', 'ncu', 'independent_profiler', applicability='gpu', tool='ncu', posthoc=True),
    Metric('gpu_executed_mflops_app_ncu', 'MFLOP/s', 'ncu', 'independent_profiler', applicability='gpu', tool='ncu', posthoc=True),
    Metric('gpu_executed_mflops_packet_ncu', 'MFLOP/s', 'ncu', 'independent_profiler', applicability='gpu', tool='ncu', posthoc=True),
    Metric('gpu_kernel_launch_count_per_request_ncu', 'count/request', 'ncu', 'independent_profiler', applicability='gpu', tool='ncu', posthoc=True),
    Metric('gpu_kernel_time_sum_ms_per_request_ncu', 'ms/request', 'ncu', 'independent_profiler', applicability='gpu', tool='ncu', posthoc=True),
    Metric('compute_profile_error_ncu', 'text', 'ncu', 'independent_profiler', applicability='gpu', kind='text', tool='ncu', posthoc=True),
    Metric('cpu_heap_peak_bytes_massif', 'byte', 'massif', 'profiler_process_lifetime', applicability='cpu', tool='massif', posthoc=True),
    Metric('cpu_heap_extra_peak_bytes_massif', 'byte', 'massif', 'profiler_process_lifetime', applicability='cpu', tool='massif', posthoc=True),
    Metric('cpu_stack_peak_bytes_massif', 'byte', 'massif', 'profiler_process_lifetime', applicability='cpu', tool='massif', posthoc=True),
    Metric('cpu_heap_peak_total_bytes_massif', 'byte', 'massif', 'profiler_process_lifetime', applicability='cpu', tool='massif', posthoc=True),
    Metric('cpu_heap_peak_at_ms_massif', 'ms', 'massif', 'profiler_process_lifetime', applicability='cpu', tool='massif', posthoc=True),
    Metric('compute_profile_error_massif', 'text', 'massif', 'profiler_process_lifetime', applicability='cpu', kind='text', tool='massif', posthoc=True),
    Metric('host_inference_wall_time_ms_per_request_nsys', 'ms/request', 'nsys', 'independent_profiler', applicability='gpu', tool='nsys', posthoc=True),
    Metric('cuda_api_time_sum_ms_per_request_nsys', 'ms/request', 'nsys', 'independent_profiler', applicability='gpu', tool='nsys', posthoc=True),
    Metric('cuda_api_call_count_per_request_nsys', 'count/request', 'nsys', 'independent_profiler', applicability='gpu', tool='nsys', posthoc=True),
    Metric('gpu_kernel_time_sum_ms_per_request_nsys', 'ms/request', 'nsys', 'independent_profiler', applicability='gpu', tool='nsys', posthoc=True),
    Metric('gpu_kernel_launch_count_per_request_nsys', 'count/request', 'nsys', 'independent_profiler', applicability='gpu', tool='nsys', posthoc=True),
    Metric('gpu_memcpy_time_sum_ms_per_request_nsys', 'ms/request', 'nsys', 'independent_profiler', applicability='gpu', tool='nsys', posthoc=True),
    Metric('gpu_memcpy_count_per_request_nsys', 'count/request', 'nsys', 'independent_profiler', applicability='gpu', tool='nsys', posthoc=True),
    Metric('gpu_memcpy_bytes_per_request_nsys', 'byte/request', 'nsys', 'independent_profiler', applicability='gpu', tool='nsys', posthoc=True),
    Metric('compute_profile_error_nsys', 'text', 'nsys', 'independent_profiler', applicability='gpu', kind='text', tool='nsys', posthoc=True),
    Metric('gpu_idle_power_w', 'W', 'nvml_device_0', 'matched_control', applicability='gpu'),
    Metric('gpu_idle_measured_at', 'ISO-8601', 'nvml_device_0', 'matched_control', applicability='gpu_idle_debug', kind='text'),
    Metric('gpu_idle_rel_range_so_far', 'ratio', 'nvml_device_0', 'case_controls_so_far', applicability='gpu_idle_debug'),
    Metric('gpu_energy_iters', 'sample/window', 'nvml_device_0', 'request_window', applicability='gpu'),
    Metric('gpu_avg_power_total_w', 'W', 'nvml_device_0', 'request_window', applicability='gpu'),
    Metric('gpu_peak_power_total_w', 'W', 'nvml_device_0', 'request_window', applicability='gpu'),
    Metric('gpu_energy_total_j', 'J/request', 'nvml_device_0', 'request_window', applicability='gpu'),
    Metric('gpu_avg_power_eff_w', 'W', 'nvml_device_0', 'request_window', applicability='gpu'),
    Metric('gpu_peak_power_eff_w', 'W', 'nvml_device_0', 'request_window', applicability='gpu'),
    Metric('gpu_energy_eff_j', 'J/request', 'nvml_device_0', 'request_window', applicability='gpu'),
    Metric('cpu_idle_power_w', 'W', 'rapl_package', 'matched_control'),
    Metric('cpu_idle_measured_at', 'ISO-8601', 'rapl_package', 'matched_control', applicability='idle_debug', kind='text'),
    Metric('cpu_idle_rel_range_so_far', 'ratio', 'rapl_package', 'case_controls_so_far', applicability='idle_debug'),
    Metric('cpu_energy_iters', 'sample/window', 'rapl_package', 'request_window'),
    Metric('cpu_avg_power_total_w', 'W', 'rapl_package', 'request_window'),
    Metric('cpu_peak_power_total_w', 'W', 'rapl_package', 'request_window'),
    Metric('cpu_energy_total_j', 'J/request', 'rapl_package', 'request_window'),
    Metric('cpu_avg_power_eff_w', 'W', 'rapl_package', 'request_window'),
    Metric('cpu_peak_power_eff_w', 'W', 'rapl_package', 'request_window'),
    Metric('cpu_energy_eff_j', 'J/request', 'rapl_package', 'request_window'),
    Metric('vcpu_cpu_share', 'ratio', 'rapl_cgroup_attribution', 'request_window'),
    Metric('vcpu_cpu_time_s', 's/request', 'rapl_cgroup_attribution', 'request_window'),
    Metric('vcpu_avg_power_total_w', 'W', 'rapl_cgroup_attribution', 'request_window'),
    Metric('vcpu_peak_power_total_w', 'W', 'rapl_cgroup_attribution', 'request_window'),
    Metric('vcpu_energy_total_j', 'J/request', 'rapl_cgroup_attribution', 'request_window'),
    Metric('vcpu_avg_power_eff_w', 'W', 'rapl_cgroup_attribution', 'request_window'),
    Metric('vcpu_peak_power_eff_w', 'W', 'rapl_cgroup_attribution', 'request_window'),
    Metric('vcpu_energy_eff_j', 'J/request', 'rapl_cgroup_attribution', 'request_window'),
    Metric('container_attributed_energy_eff_j', 'J/request', 'derived', 'request_window'),
    Metric('container_attributed_samples_per_j', 'sample/J', 'derived', 'request_window'),
    Metric('container_attributed_edp_app_js', 'J*s/request', 'derived', 'request_window'),
    Metric('output_tokens_per_s_app', 'token/s', 'client_http', 'request_window', applicability='text_tokenizer'),
    Metric('container_attributed_j_per_output_token', 'J/token', 'derived', 'request_window', applicability='text_tokenizer'),
    Metric('container_attributed_j_per_input_unit', 'J/input_unit', 'derived', 'request_window'),
    Metric('container_attributed_j_per_input_megapixel', 'J/Mpixel', 'derived', 'request_window', applicability='pixel_geometry'),
    Metric('container_attributed_j_per_output_megapixel', 'J/Mpixel', 'derived', 'request_window', applicability='pixel_geometry'),
    Metric('resource_usage_iters', 'sample/window', 'cgroup', 'request_window'),
    Metric('container_cpu_util_avg_pct', '%', 'cgroup', 'request_window'),
    Metric('container_cpu_util_peak_pct', '%', 'cgroup', 'request_window'),
    Metric('container_cpu_nr_periods_delta', 'count/window', 'cgroup', 'request_window'),
    Metric('container_cpu_nr_throttled_delta', 'count/window', 'cgroup', 'request_window'),
    Metric('container_cpu_throttled_period_ratio_pct', '%', 'cgroup', 'request_window'),
    Metric('container_cpu_throttled_time_s_per_request', 's/request', 'cgroup', 'request_window'),
    Metric('container_cpu_pressure_some_stall_pct', '%', 'cgroup', 'request_window'),
    Metric('container_cpu_pressure_full_stall_pct', '%', 'cgroup', 'request_window'),
    Metric('cpu_freq_avg_hz', 'Hz', 'host_cpufreq', 'request_window'),
    Metric('cpu_freq_peak_hz', 'Hz', 'host_cpufreq', 'request_window'),
    Metric('cpu_cycles_est_app', 'cycle/request', 'derived', 'request_window'),
    Metric('cpu_cycles_est_packet', 'cycle/request', 'derived', 'request_window'),
    Metric('cpu_instructions_per_request', 'count/request', 'perf_stat', 'request_window'),
    Metric('cpu_mips_app', 'Minstruction/s', 'perf_stat', 'request_window'),
    Metric('cpu_mips_packet', 'Minstruction/s', 'perf_stat', 'request_window'),
    Metric('cpu_perf_elapsed_s', 's', 'perf_stat', 'request_window'),
    Metric('cpu_cache_references_per_request', 'count/request', 'perf_stat', 'request_window'),
    Metric('cpu_cache_misses_per_request', 'count/request', 'perf_stat', 'request_window'),
    Metric('cpu_cache_miss_rate_pct', '%', 'perf_stat', 'request_window'),
    Metric('cpu_dtlb_loads_per_request', 'count/request', 'perf_stat', 'request_window'),
    Metric('cpu_dtlb_load_misses_per_request', 'count/request', 'perf_stat', 'request_window'),
    Metric('cpu_dtlb_load_miss_rate_pct', '%', 'perf_stat', 'request_window'),
    Metric('container_mem_usage_avg_bytes', 'byte', 'cgroup', 'request_window'),
    Metric('container_mem_usage_peak_bytes', 'byte', 'cgroup', 'request_window'),
    Metric('container_mem_util_avg_pct', '%', 'cgroup', 'request_window'),
    Metric('container_mem_util_peak_pct', '%', 'cgroup', 'request_window'),
    Metric('container_mem_peak_cgroup_bytes', 'byte', 'cgroup', 'cgroup_lifetime'),
    Metric('container_mem_anon_bytes_end', 'byte', 'cgroup', 'request_window_end'),
    Metric('container_mem_file_bytes_end', 'byte', 'cgroup', 'request_window_end'),
    Metric('container_mem_slab_bytes_end', 'byte', 'cgroup', 'request_window_end'),
    Metric('container_mem_pgfault_delta', 'count/window', 'cgroup', 'request_window'),
    Metric('container_mem_pgmajfault_delta', 'count/window', 'cgroup', 'request_window'),
    Metric('container_mem_workingset_refault_delta', 'count/window', 'cgroup', 'request_window'),
    Metric('container_mem_high_events_delta', 'count/window', 'cgroup', 'request_window'),
    Metric('container_mem_max_events_delta', 'count/window', 'cgroup', 'request_window'),
    Metric('container_mem_oom_events_delta', 'count/window', 'cgroup', 'request_window'),
    Metric('container_mem_oom_kill_events_delta', 'count/window', 'cgroup', 'request_window'),
    Metric('container_mem_pressure_some_stall_pct', '%', 'cgroup', 'request_window'),
    Metric('container_mem_pressure_full_stall_pct', '%', 'cgroup', 'request_window'),
    Metric('container_swap_limit_bytes', 'byte', 'cgroup', 'request_window'),
    Metric('container_swap_usage_avg_bytes', 'byte', 'cgroup', 'request_window'),
    Metric('container_swap_usage_peak_bytes', 'byte', 'cgroup', 'request_window'),
    Metric('container_io_read_bytes_per_request', 'byte/request', 'cgroup', 'request_window'),
    Metric('container_io_write_bytes_per_request', 'byte/request', 'cgroup', 'request_window'),
    Metric('container_io_read_ops_per_request', 'count/request', 'cgroup', 'request_window'),
    Metric('container_io_write_ops_per_request', 'count/request', 'cgroup', 'request_window'),
    Metric('container_io_pressure_some_stall_pct', '%', 'cgroup', 'request_window'),
    Metric('container_io_pressure_full_stall_pct', '%', 'cgroup', 'request_window'),
    Metric('container_pids_current_end', 'count', 'cgroup', 'request_window_end'),
    Metric('container_pids_peak_cgroup', 'count', 'cgroup', 'cgroup_lifetime'),
    Metric('container_pids_max_events_delta', 'count/window', 'cgroup', 'request_window'),
    Metric('gpu_sm_clock_mhz', 'MHz', 'nvml_device_0', 'request_window', applicability='gpu'),
    Metric('gpu_memory_clock_mhz', 'MHz', 'nvml_device_0', 'request_window', applicability='gpu'),
    Metric('gpu_pstate', 'text', 'nvml_device_0', 'request_window', applicability='gpu', kind='text'),
    Metric('gpu_temp_c', 'degC', 'nvml_device_0', 'request_window', applicability='gpu'),
    Metric('gpu_util_avg_pct', '%', 'nvml_device_0', 'request_window', applicability='gpu'),
    Metric('gpu_util_peak_pct', '%', 'nvml_device_0', 'request_window', applicability='gpu'),
    Metric('gpu_mem_used_avg_bytes', 'byte', 'nvml_device_0', 'request_window', applicability='gpu'),
    Metric('gpu_mem_used_peak_bytes', 'byte', 'nvml_device_0', 'request_window', applicability='gpu'),
    Metric('gpu_mem_util_avg_pct', '%', 'nvml_device_0', 'request_window', applicability='gpu'),
    Metric('gpu_mem_util_peak_pct', '%', 'nvml_device_0', 'request_window', applicability='gpu'),
    Metric('cold_start_started_at', 'ISO-8601', 'docker_and_server', 'container_startup', kind='text'),
    Metric('cold_start_ready_at', 'ISO-8601', 'docker_and_server', 'container_startup', kind='text'),
    Metric('cold_start_container_launch_s', 's', 'docker_and_server', 'container_startup'),
    Metric('cold_start_server_setup_s', 's', 'docker_and_server', 'container_startup'),
    Metric('cold_start_cuda_init_s', 's', 'docker_and_server', 'container_startup'),
    Metric('cold_start_model_load_s', 's', 'docker_and_server', 'container_startup'),
    Metric('cold_start_ready_wait_s', 's', 'docker_and_server', 'container_startup'),
    Metric('cold_start_first_predict_app_s', 's', 'docker_and_server', 'container_startup'),
    Metric('cold_start_s', 's', 'docker_and_server', 'container_startup'),
    Metric('status', 'text', 'protocol', 'row', kind='text'),
    Metric('error', 'text', 'protocol', 'row', kind='text'),
)
METRICS = MappingProxyType({metric.name: metric for metric in _DECLARATIONS})
if len(METRICS) != len(_DECLARATIONS):
    raise ValueError("指标登记表包含重复字段")
CSV_FIELDS = list(METRICS)
NUMERIC_FIELDS = tuple(name for name, metric in METRICS.items() if metric.kind == "number")
GPU_RUNTIME_STATE_FIELDS = ["gpu_sm_clock_mhz", "gpu_memory_clock_mhz", "gpu_pstate", "gpu_temp_c"]


def tool_fields(tool: str, *, numeric_only: bool = False) -> tuple[str, ...]:
    return tuple(name for name, metric in METRICS.items()
                 if metric.tool == tool and metric.posthoc and (not numeric_only or metric.kind == "number"))
