ARG MODEL_IMAGE
FROM ${MODEL_IMAGE}
ARG RUNTIME_PROFILE
ARG MODEL_ADAPTER=family-default
ARG BUILD_FINGERPRINT
ARG DEPENDENCY_LOCK_SHA256
ENV ACPROF_RUNTIME_PROFILE=${RUNTIME_PROFILE} ACPROF_MODEL_ADAPTER=${MODEL_ADAPTER}
ENV ACPROF_BUILD_FINGERPRINT=${BUILD_FINGERPRINT} ACPROF_DEPENDENCY_LOCK_SHA256=${DEPENDENCY_LOCK_SHA256}
LABEL org.acprof.build-fingerprint=${BUILD_FINGERPRINT} \
      org.acprof.runtime-profile=${RUNTIME_PROFILE} org.acprof.model-adapter=${MODEL_ADAPTER}
COPY acprof/ /app/acprof/
RUN python -m acprof.container.runtime_manifest
CMD ["python", "-m", "acprof.container.server"]
