ARG MODEL_IMAGE
FROM ${MODEL_IMAGE}
ARG RUNTIME_PROFILE
ARG MODEL_ADAPTER=family-default
ARG BUILD_FINGERPRINT
ARG DEPENDENCY_LOCK_SHA256
ARG REQUEST_FINGERPRINT
ARG PLATFORM_IMAGE_ID
ARG ENVIRONMENT_IMAGE_ID
ARG MODEL_IMAGE_ID
ARG MODEL_SPEC_B64=
ENV ACPROF_MODEL_SPEC_B64=${MODEL_SPEC_B64}
ENV ACPROF_RUNTIME_PROFILE=${RUNTIME_PROFILE} ACPROF_MODEL_ADAPTER=${MODEL_ADAPTER}
ENV ACPROF_BUILD_FINGERPRINT=${BUILD_FINGERPRINT} ACPROF_DEPENDENCY_LOCK_SHA256=${DEPENDENCY_LOCK_SHA256}
ENV ACPROF_REQUEST_FINGERPRINT=${REQUEST_FINGERPRINT} ACPROF_PLATFORM_IMAGE_ID=${PLATFORM_IMAGE_ID} \
    ACPROF_ENVIRONMENT_IMAGE_ID=${ENVIRONMENT_IMAGE_ID} ACPROF_MODEL_IMAGE_ID=${MODEL_IMAGE_ID}
LABEL org.acprof.build-fingerprint=${BUILD_FINGERPRINT} \
      org.acprof.request-fingerprint=${REQUEST_FINGERPRINT} \
      org.acprof.runtime-profile=${RUNTIME_PROFILE} org.acprof.model-adapter=${MODEL_ADAPTER} \
      org.acprof.image-kind="model"
COPY acprof/ /app/acprof/
RUN python -m acprof.container.runtime_manifest
CMD ["python", "-m", "acprof.container.server"]
